### ISSUE TITLE
node red crashes every a couple of hours.

### ISSUE THREAD

**Issue by WojtekWro** [NorthernMan54/node-red-contrib-homebridge-automation#112]
Hi guys. 
Could someone help me with this? 

Every couple of hours nod-red crashes and restarts. 
I use many homebridge nodes and it is hard to investigate which of them can caused this crash. 

I don't know for how long I have this problem. I noticed this when I started using global variables, and they ware gone every time, a couple of hour after restart.

Log shows only this. 

```
6 Mar 15:16:34 - [red] Uncaught Exception:
6 Mar 15:16:34 - [error] TypeError: Cannot read properties of undefined (reading 'replace')
    at new Characteristic (/data/node_modules/node-red-contrib-homebridge-automation/lib/Characteristic.js:22:41)
    at Service.<anonymous> (/data/node_modules/node-red-contrib-homebridge-automation/lib/Service.js:88:19)
    at Array.forEach (<anonymous>)
    at new Service (/data/node_modules/node-red-contrib-homebridge-automation/lib/Service.js:87:27)
    at Accessory.<anonymous> (/data/node_modules/node-red-contrib-homebridge-automation/lib/Accessory.js:35:23)
    at Array.forEach (<anonymous>)
    at new Accessory (/data/node_modules/node-red-contrib-homebridge-automation/lib/Accessory.js:20:20)
    at Homebridge.<anonymous> (/data/node_modules/node-red-contrib-homebridge-automation/lib/Homebridge.js:51:21)
    at Array.forEach (<anonymous>)
    at new Homebridge (/data/node_modules/node-red-contrib-homebridge-automation/lib/Homebridge.js:50:35)
6 Mar 15:16:37 - [info] 
```

**Comment by NorthernMan54** [comment]
I think I was able to resolve this, please update to the latest version `v0.1.9` and let me know.

**Comment by WojtekWro** [comment]
I am sorry for this question, but could you tell me, how can I update it? 
I am still on v0.1.4 and in Palette see no updates.

**Comment by WojtekWro** [comment]
Thank you. I update it. I will let you know if the issue is solved :-)
Thanks again.

**Comment by WojtekWro** [comment]
@NorthernMan54 My Node-red is up for 40 hours now. I think the problem is solved :-) 
Thank you
