### ISSUE TITLE
HA crashes node-red

### ISSUE THREAD

**Issue by Einstein2150** [NorthernMan54/node-red-contrib-homebridge-automation#115]
### Analysis

node-red crashes after some time.

### Expected Behavior

node-red runs without crash

### Steps To Reproduce

just run and wait ...

### Logs

```markdown
Okt 18 04:54:28 raspberrypi systemd[1]: Started nodered.service - Node-RED graphical event wiring tool.
Okt 18 04:54:28 raspberrypi systemd[1]: nodered.service: Consumed 3h 27min 57.980s CPU time.
Okt 18 04:54:28 raspberrypi systemd[1]: Stopped nodered.service - Node-RED graphical event wiring tool.
Okt 18 04:54:28 raspberrypi systemd[1]: nodered.service: Scheduled restart job, restart counter is at 1.
Okt 18 04:54:08 raspberrypi systemd[1]: nodered.service: Consumed 3h 27min 57.980s CPU time.
Okt 18 04:54:08 raspberrypi systemd[1]: nodered.service: Failed with result 'exit-code'.
Okt 18 04:54:08 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at Tickets.<computed> [as failed] (/home/pi/.node-red/node_modules/better-queue/lib/tickets.js:30:10)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at Tickets._apply (/home/pi/.node-red/node_modules/better-queue/lib/tickets.js:9:16)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at Array.forEach (<anonymous>)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at /home/pi/.node-red/node_modules/better-queue/lib/tickets.js:10:16
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at Ticket.failed (/home/pi/.node-red/node_modules/better-queue/lib/ticket.js:49:8)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at Ticket.emit (node:events:517:28)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at Ticket.<anonymous> (/home/pi/.node-red/node_modules/better-queue/lib/queue.js:235:38)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at hbEvent.<anonymous> (/home/pi/.node-red/node_modules/red-contrib-homebridge-automation/HAP-NodeRed.js:173:9)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at _status (/home/pi/.node-red/node_modules/red-contrib-homebridge-automation/HAP-NodeRed.js:660:24)
Okt 18 04:54:08 raspberrypi Node-RED[9783]:     at HAPNodeJSClient.HAPstatus (/home/pi/.node-red/node_modules/hap-node-client/HAPNodeJSClient.js:672:19)
Okt 18 04:54:08 raspberrypi Node-RED[9783]: 18 Oct 04:54:08 - [error] TypeError: Cannot read properties of undefined (reading 'url')
Okt 18 04:54:08 raspberrypi Node-RED[9783]: 18 Oct 04:54:08 - [red] Uncaught Exception:
Okt 18 04:54:08 raspberrypi Node-RED[9783]: 2023-10-18T02:54:08.513Z hapNodeRed _status request: Smart lock cylinder - Battery Service -> 192.168.2.200:51163 -> ?id=40>
Okt 18 04:54:08 raspberrypi Node-RED[9783]: 2023-10-18T02:54:08.480Z hapNodeRed hbEvent.register Smart lock cylinder - Battery Service
Okt 18 04:49:16 raspberrypi Node-RED[9783]: 2023-10-18T02:49:16.376Z hapNodeRed Discovered 183 new ctDevices
Okt 18 04:49:16 raspberrypi Node-RED[9783]: 2023-10-18T02:49:16.365Z hapNodeRed Discovered 191 new evDevices
Okt 18 04:49:16 raspberrypi Node-RED[9783]: 2023-10-18T02:49:16.318Z hapNodeJSClient Ready
Okt 18 04:48:56 raspberrypi Node-RED[9783]: 2023-10-18T02:48:56.895Z hapNodeJSClient Homebridge instance discovered Pi-Homebridge2 CAD8 @ http://192.168.2.200:51163 wi>
Okt 18 04:48:56 raspberrypi Node-RED[9783]: ]
Okt 18 04:48:56 raspberrypi Node-RED[9783]:   'fe80::1ce5:5546:90e7:fae5'
Okt 18 04:48:56 raspberrypi Node-RED[9783]:   '2003:d7:2f42:ba00:bc0d:f0c9:db81:c8a1',
Okt 18 04:48:56 raspberrypi Node-RED[9783]:   'fe80::28aa:ccff:8b7b:aba4',
Okt 18 04:48:56 raspberrypi Node-RED[9783]:   '2003:d7:2f42:ba00:f2df:e724:4da7:6e6',
Okt 18 04:48:56 raspberrypi Node-RED[9783]:   '192.168.2.68',
Okt 18 04:48:56 raspberrypi Node-RED[9783]:   '192.168.2.200',
Okt 18 04:48:56 raspberrypi Node-RED[9783]: 2023-10-18T02:48:56.313Z hapNodeJSClient HAP Device discovered Pi-Homebridge2 CAD8 [
```

### Configuration

```json
none
```

### Environment

- OS: raspbian bookworm
- Software: homebridge 1.6.1
- Node: 18.18.2
- npm: 9.8.1

### Process Supervisor

hb-service

**Comment by Einstein2150** [comment]
Sorry for this issue here. Meanwhile I found the problem. While migrating to the new bookworm-release with the reconfiguration of node-red I mixed "red-contrib-homebridge-automation" with "node-red-contrib-homebridge-automation".

red-contrib-homebridge-automation is making the problem. Switching to node-red-contrib-homebridge-automation fixes the issues and everything is working as expected.
