### ISSUE TITLE
Install - fatal: could not create leading directories

### ISSUE THREAD

**Issue by bakman2** [NorthernMan54/node-red-contrib-homebridge-automation#17]
$ uname -a 
Linux homeautomation 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux

With and without root both state:
```
$ more /root/.npm/_logs/2019-07-27T11_16_24_327Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/NorthernMan54/node-red-contrib-homebridge-automation' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 0b7381e2a6a842aa
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.git C
ommand failed: git clone --mirror -q https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.git /root/.
npm/_cacache/tmp/git-clone-ba274e94/.git
7 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ba274e94/
.git'
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 481ms
10 verbose stack Error: Command failed: git clone --mirror -q https://github.com/NorthernMan54/node-red-contrib-homebrid
ge-automation.git /root/.npm/_cacache/tmp/git-clone-ba274e94/.git
10 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ba274e94/.git'
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
10 verbose stack     at ChildProcess.emit (events.js:198:13)
10 verbose stack     at maybeClose (internal/child_process.js:982:16)
10 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
10 verbose stack     at Socket.emit (events.js:198:13)
10 verbose stack     at Pipe._handle.close (net.js:606:12)
11 verbose cwd /home/administrator/.node-red
12 verbose Linux 4.9.0-9-amd64
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "https://github.com/NorthernMan54/node-red-contrib-homebri
dge-automation"
14 verbose node v10.16.0
15 verbose npm  v6.9.0
16 error code 128
17 error Command failed: git clone --mirror -q https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.g
it /root/.npm/_cacache/tmp/git-clone-ba274e94/.git
17 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ba274e94/.git'
18 verbose exit [ 1, true ]
```

**Edit** 
`npm install -g hap-nodered`
works.

**Comment by NorthernMan54** [comment]
I changed the packaging, and republished via NPM.

Try installing like this

```
    cd ~/.node-red
    npm install node-red-contrib-homebridge-automation
```

**Comment by bakman2** [comment]
@NorthernMan54 thanks, it works.

Is there a limitation to what this node detects/can read from homebridge ?
I am using homebridge-mqtt, I don't see it the devices I added. (I don't need this to work, but was testing).

**Comment by NorthernMan54** [comment]
It should show everything, the only limitation would be the new TV accessories.

**Comment by bakman2** [comment]
Got it. Forgot the insecure mode, restarted homebridge and node-red. Now everything shows up. Nice, I will play around, thanks.

**Comment by NorthernMan54** [comment]
Awesome
